### ISSUE TITLE
Allow hasql-pool-0.8

### ISSUE THREAD

**Issue by robx** [diogob/hasql-notifications#12]
There's a new release 0.8 of hasql-pool https://hackage.haskell.org/package/hasql-pool which we'd like to use in PostgREST alongside hasql-notifications, so it'd be great if you could relax the upper bound. (I think the parts of the API relevant to hasql-notifications haven't changed, so it should be just the bounds change.)

**Comment by diogob** [comment]
@robx thanks for opening the issue. The tests ran fine with the new version. I have just published `0.2.0.3` to hackage with the new version constraints. Please let me know if you need any further help.
