### ISSUE TITLE
`waitForNotifications` not handling NOTIFY commands on Windows

### ISSUE THREAD

**Issue by laurenceisla** [diogob/hasql-notifications#17]
When doing a NOTIFY in Windows, it does not handle the notification as if nothing was done. It seems that the problem is with `threadWaitRead`, I tested changing it to `threadDelay` and the notification worked (for reference:   https://github.com/PostgREST/postgrest/pull/2906#discussion_r1296703798).

Any idea on how we could solve this?

**Comment by diogob** [comment]
Thanks for reporting @laurenceisla . I just read the thread on PostgREST repo. I have some ideas, but still need to do more research. I'll try to setup a windows testing environment.

**Comment by diogob** [comment]
That is the postgresql-simple solution: https://github.com/haskellari/postgresql-simple/blob/master/src/Database/PostgreSQL/Simple/Notification.hs#L87
