### ISSUE TITLE
Swagger documentation with Postgrest api

### ISSUE THREAD

**Issue by ramujava412** [diogob/hasql-notifications#19]
Dear Team,

I hope this message finds you well. I am currently working on incorporating Swagger documentation for PostgREST, and I have encountered an issue related to multiple schemas defined for the database.

db-schemas = "test1,test2";

The specific issue I'm facing pertains to the "db-schemas" configuration, where I have specified multiple schemas as follows: "test1" and "test2." However, when attempting to access the Swagger documentation, I have observed that it only generates documentation for "test1" and does not include information for the other schema, namely "test2."

I would greatly appreciate your assistance in addressing this matter and ensuring that the Swagger documentation encompasses all specified schemas. Your technical expertise and guidance on this issue would be immensely valuable.

Thank you for your time and support.

Best regards,
Ram

**Comment by diogob** [comment]
@Rameswar143 I do believe you meant to open this at https://github.com/postgrest/postgrest. Please reopen if there is something on `hsql-notifications` where I could help.
