### ISSUE TITLE
Don't ignore error message on `PQ.consumeInput`

### ISSUE THREAD

**Issue by steve-chavez** [diogob/hasql-notifications#20]
Hey @diogob,

On https://github.com/PostgREST/postgrest/discussions/3313#discussioncomment-8756677, a user reports the LISTEN channel is getting killed and we're getting a generic error message from hasql-notifications which comes from:

https://github.com/diogob/hasql-notifications/blob/b072182801bbc73409135b64a484ca58eee39c24/src/Hasql/Notifications.hs#L167

There might be more details on `PQ.consumeInput`, since according to pg docs:

> [PQconsumeInput](https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQCONSUMEINPUT) normally returns 1 indicating “no error”, but returns 0 if there was some kind of trouble (in which case [PQerrorMessage](https://www.postgresql.org/docs/current/libpq-status.html#LIBPQ-PQERRORMESSAGE) can be consulted).

However `PQ.consumeInput` result is getting ignored on:

https://github.com/diogob/hasql-notifications/blob/b072182801bbc73409135b64a484ca58eee39c24/src/Hasql/Notifications.hs#L175

**Comment by diogob** [comment]
Hi @steve-chavez , would a panic with some custom message work on your side? I can get the string from `PQerrorMessage` and default to the generic one when no string is available (comes inside a `Maybe`).

It could be the case that the call to `PQsocket` is failing during the connection setup (I think that panic should not be there, perhaps just using a delay will fix the issue).

I'll work on a PR to fix this.

**Comment by diogob** [comment]
@steve-chavez I just put together a quick attempt to address the issue on #21  but haven't tested it. Are you able to use the version from that branch and verify if the behaviour change would satisfy your case?

**Comment by diogob** [comment]
@steve-chavez just published [0.2.1.0](https://hackage.haskell.org/package/hasql-notifications)
