### ISSUE TITLE
`listen` silently fails on a read replica

### ISSUE THREAD

**Issue by steve-chavez** [diogob/hasql-notifications#24]
Read replicas fail on LISTEN:

```sql
postgres=# LISTEN pgrst;
ERROR:  cannot execute LISTEN during recovery

postgres=# select pg_is_in_recovery();
 pg_is_in_recovery 
-------------------
 t
(1 row)

# Also see https://stackoverflow.com/questions/70293290/can-you-perform-listen-unlisten-on-a-postgresql-read-replica
```

This currently fails silently on `hasql-notifications`, due to `listen` ignoring the error (`void`):

https://github.com/diogob/hasql-notifications/blob/c8f4956c2ee58ad619faa3a6c21bf968b1190b0c/src/Hasql/Notifications.hs#L120

Note: UNLISTEN doesn't fail on the replica, but it would still be good to not ignore the error there too.

**Comment by diogob** [comment]
thanks for the report @steve-chavez , will fix it.
