### ISSUE TITLE
integration with servant-server streams 

### ISSUE THREAD

**Issue by docteurklein** [diogob/hasql-notifications#3]
Hello :)

I tried with this library and https://github.com/jfischoff/hasql-notifications without any success,
but I'd like to stream Server-Sent-Events to http clients as they come.

You can see both tentatives here https://github.com/docteurklein/haskell-pg-sse/blob/master/src/Main.hs#L135.

Any idea how I could make it work?

**Comment by docteurklein** [comment]
Something else I wonder is how to use a hasql pool to **listen** and wait for notifications?

**Comment by diogob** [comment]
@docteurklein sorry for the delayed response. About the hasql pool, it's not really a good use case since listening for notifications changes the state of the connection and that would force you to keep it out of hte pool. So a dedicated connection becomes necessary.
