### ISSUE TITLE
Don't panic on waitForNotifications

### ISSUE THREAD

**Issue by steve-chavez** [diogob/hasql-notifications#4]
Hey @diogob,

I was wondering if it would be possible to not [panic on waitForNotifications](https://github.com/diogob/hasql-notifications/blob/master/src/Hasql/Notifications.hs#L162) and instead  return an `IO Either`. Similar to what hasql does in [Connection.acquire](https://hackage.haskell.org/package/hasql-1.4.3/docs/Hasql-Connection.html#v:acquire) or [Pool.use](https://hackage.haskell.org/package/hasql-pool-0.5.2/docs/Hasql-Pool.html#v:use).

The use case is to be able to retry `waitForNotifications` from the same thread if the connection fails. This is related to https://github.com/PostgREST/postgrest/pull/1542.

Thanks!

**Comment by diogob** [comment]
@steve-chavez could you give me a code example of how the interface would look like? 
I'm assuming this is the call site: https://github.com/PostgREST/postgrest/pull/1542/files#diff-cf0c4471495584a946dc7035028102e7R156

It seems to me that a `forkFinally` might solve your use case.

**Comment by steve-chavez** [comment]
@diogob Thanks a lot for the `forkFinally` suggestion :). Looks like it could work, I'll let you know.
