### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by robx** [diogob/hasql-notifications#5]
Hi! I'm taking care of the dependency side of postgrest, and particularly of maintaining it for stackage. Since hasql-notifications is a new dependency, for that to keep working out I kind of need hasql-notifications to be added to stackage. Would you be willing to do that?

It's a matter of making a small PR against [commercialhaskell/stackage](https://github.com/commercialhaskell/stackage), compare the docs on [Adding a package](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package). Here's an example back from when I added configurator-pg: https://github.com/commercialhaskell/stackage/pull/4609/files. I've already checked that hasql-notifications builds fine with current stackage nightly, so there should be no technical issues.

**Comment by robx** [comment]
> I've already checked that hasql-notifications builds fine with current stackage nightly, so there should be no technical issues.

Turns out I made a mistake, there's some test failures. Trying to fix.

EDIT: Oh, obviously, the tests need postgres, so they would have to be skipped for stackage's CI. Compare the PR where we added postgrest, that also has its tests skipped: https://github.com/commercialhaskell/stackage/pull/5308/files

**Comment by diogob** [comment]
@robx thanks for all the tips. I'm most definitely interested in adding this package to stackage. I'll work on this.

**Comment by diogob** [comment]
this https://github.com/commercialhaskell/stackage/pull/5600 should take care of this issue.

**Comment by diogob** [comment]
Confirmed in stackage nightly https://www.stackage.org/nightly-2020-08-16/package/hasql-notifications-0.1.0.0
