### ISSUE TITLE
After receiving a notification, the next query hangs

### ISSUE THREAD

**Issue by chris-martin** [diogob/hasql-notifications#7]
I just tried hasql-notifications for the first time. My program runs like this:

- It opens a single connection for the whole program.
- It does an initial select query on that connection;
- then calls `waitForNotifications`.
- My handler performs that same select query.

The first time the query runs, it completes successfully. The second time, when it runs in the notification handler, it blocks indefinitely.

If I modify the program to use two separate connections - one for notification listening, the second for all other queries - then things seems to run as expected.

Is this pattern, where I'm trying to listen and query on the same connection, meant to be supported? I was doing it successfully with postgresql-simple before.

I'm using hasql-notifications 0.2.0.0 and Postgres 12.

**Comment by diogob** [comment]
You are correct, `waitForNotifications` will indeed block the connection, I'll improve the docs to make this clear.
Does your use case requires doing everything in the same connection?

**Comment by chris-martin** [comment]
No, it doesn't require doing everything in the same connection, and I've already refactored everything to use a separate connection and a separate thread for the listening. I had been doing everything on a single connection before just to avoid opening unnecessarily many connections, but I suppose it doesn't really make much difference.
